services:
  redis-node1:
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    sysctls:
    - net.core.somaxconn=65535
    container_name: redis-node1
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - "127.0.1.1:6379:6379"
    environment:
      REDIS_ROLE: cluster-node
      REDIS_ANNOUNCE_IP: redis-node1
    networks:
      - redis-network

  redis-node2:
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    sysctls:
    - net.core.somaxconn=65535
    container_name: redis-node2
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - "127.0.1.2:6379:6379"
    environment:
      REDIS_ROLE: cluster-node
      REDIS_ANNOUNCE_IP: redis-node2
    networks:
      - redis-network

  redis-node3:
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    sysctls:
    - net.core.somaxconn=65535
    container_name: redis-node3
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - "127.0.1.3:6379:6379"
    environment:
      REDIS_ROLE: cluster-node
      REDIS_ANNOUNCE_IP: redis-node3
    networks:
      - redis-network

  redis-starter:
    restart: no
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    container_name: redis-starter
    depends_on:
      redis-node1:
        condition: service_healthy
      redis-node2:
        condition: service_healthy
      redis-node3:
        condition: service_healthy
    environment:
      REDIS_ROLE: cluster-starter
      REDIS_ANNOUNCE_IP: redis-starter
      REDIS_CLUSTER_NODES: redis-node1,redis-node2,redis-node3
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

