services:
  redis-sentinel:
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    sysctls:
    - net.core.somaxconn=65535
    container_name: redis-sentinel
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 26379 ping | grep PONG"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - "127.0.1.1:6379:6379"
    environment:
      REDIS_ROLE: sentinel
      REDIS_ANNOUNCE_IP: redis-sentinel
      REDIS_MAIN_NAME: "fluffy"
      REDIS_MONITOR_HOST: redis-node1
    depends_on:
      redis-node1:
        condition: service_healthy
      redis-node2:
        condition: service_healthy
      redis-node3:
        condition: service_healthy
    networks:
      - redis-network

  redis-node1:
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    sysctls:
    - net.core.somaxconn=65535
    container_name: redis-node1
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - "127.0.1.2:6379:6379"
    environment:
      REDIS_ROLE: primary
      REDIS_ANNOUNCE_IP: redis-node1
    networks:
      - redis-network

  redis-node2:
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    sysctls:
    - net.core.somaxconn=65535
    container_name: redis-node2
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - "127.0.1.3:6379:6379"
    environment:
      REDIS_ROLE: replica
      REDIS_ANNOUNCE_IP: redis-node2
      REDIS_PRIMARY_HOST: redis-node1
    networks:
      - redis-network

  redis-node3:
    image: registry.gitlab.com/gitlab-org/container-registry/redis-ci:bookworm
    sysctls:
    - net.core.somaxconn=65535
    container_name: redis-node3
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    ports:
      - "127.0.1.4:6379:6379"
    environment:
      REDIS_ROLE: replica
      REDIS_ANNOUNCE_IP: redis-node3
      REDIS_PRIMARY_HOST: redis-node1
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
