x-healthcheck-common: &healthcheck-common
  test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  interval: 3s
  timeout: 2s
  retries: 5
  start_period: 3s

x-kv-common: &kv-common
  image: registry.gitlab.com/gitlab-org/container-registry/kv-ci-redis:bookworm
  sysctls:
    - net.core.somaxconn=65535
  networks:
    - kv-network

services:
  redis-node1:
    <<: *kv-common
    container_name: redis-node1
    healthcheck:
      <<: *healthcheck-common
    ports:
      - "127.0.1.1:6379:6379"
    environment:
      KV_TYPE: redis
      KV_ROLE: cluster-node
      KV_ANNOUNCE_IP: redis-node1

  redis-node2:
    <<: *kv-common
    container_name: redis-node2
    healthcheck:
      <<: *healthcheck-common
    ports:
      - "127.0.1.2:6379:6379"
    environment:
      KV_TYPE: redis
      KV_ROLE: cluster-node
      KV_ANNOUNCE_IP: redis-node2

  redis-node3:
    <<: *kv-common
    container_name: redis-node3
    healthcheck:
      <<: *healthcheck-common
    ports:
      - "127.0.1.3:6379:6379"
    environment:
      KV_TYPE: redis
      KV_ROLE: cluster-node
      KV_ANNOUNCE_IP: redis-node3

  redis-starter:
    <<: *kv-common
    restart: no
    container_name: redis-starter
    depends_on:
      redis-node1:
        condition: service_healthy
      redis-node2:
        condition: service_healthy
      redis-node3:
        condition: service_healthy
    environment:
      KV_TYPE: redis
      KV_ROLE: cluster-starter
      KV_ANNOUNCE_IP: redis-starter
      KV_CLUSTER_NODES: redis-node1,redis-node2,redis-node3

networks:
  kv-network:
    driver: bridge
